export const Flowers = [
    {
        id: 0,
        color: 'red',
        isActive: false,
        xMin: 26,
        xMax: 40,
        yMax: -40,
        yMin: -54,
        currentAnchor: 1,
        maxAnchor: 2,
    },
    {
        id: 1,
        color: 'violet',
        isActive: false,
        xMin: 10,
        xMax: 24,
        yMax: -60,
        yMin: -74,
        currentAnchor: 1,
        maxAnchor: 2,
    },
    {
        id: 2,
        color: 'lightblue',
        isActive: false,
        xMin: -7,
        xMax: 7,
        yMax: -40,
        yMin: -54,
        currentAnchor: 1,
        maxAnchor: 2,
    },
    {
        id: 3,
        color: 'orange',
        isActive: false,
        xMin: -22,
        xMax: -8,
        yMax: -60,
        yMin: -74,
        currentAnchor: 1,
        maxAnchor: 2,
    },
    {
        id: 4,
        color: 'white',
        isActive: false,
        xMin: -37,
        xMax: -23,
        yMax: -40,
        yMin: -54,
        currentAnchor: 1,
        maxAnchor: 2,
    }
]